

import java.sql.Connection;
import java.sql.Date;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Leaveentry.java
 *
 * Created on Aug 27, 2014, 10:05:43 PM
 */

/**
 *
 * @author 2
 */
public class Leaveentry extends javax.swing.JFrame {

    /** Creates new form Leaveentry */
    public Leaveentry() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c1 = new datechooser.beans.DateChooserCombo();
        c2 = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEAVE ENTRY FORM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee id");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 120, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 30, 20));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 190, 30));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 190, 30));

        b3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        b3.setText("ADD");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 80, 40));

        b4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(51, 51, 51));
        b4.setText("CLEAR");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 100, 40));

        b1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        b1.setText("Back");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 120, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 150, 20));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Leave Entry");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 190, 30));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 190, 30));

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 190, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reason");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shivani Rajput\\Downloads\\WhatsApp Image 2021-01-17 at 12.24.46 PM.jpeg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 920, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
  t1.setText("");
  t2.setText("");
  ta1.setText("");
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String eid,ename,Leaveid = null, reason;
        int y,m,d;        
       
        eid=t1.getText();
        ename=t2.getText();
        reason = ta1.getText();
        
        Calendar C=c1.getSelectedDate();
        d=C.get(C.DAY_OF_MONTH);
        m=C.get(C.MONTH)+1;
        y=C.get(C.YEAR);
      
        String frm=(y+"-"+m+"-"+d);

        Calendar C1=c2.getSelectedDate();
        int d1=C1.get(C1.DAY_OF_MONTH);
        int m1=C1.get(C1.MONTH)+1;
        int y1=C1.get(C1.YEAR);
        String till=(y1+"-"+m1+"-"+d1);
       Date date1 = new Date(y, m, d); 
       Date date2 = new Date(y1, m1, d1);  
       
  //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-mm-dd");
    //Date date1 = (Date) dtf.parse(frm);
    //Date date2 = (Date) dtf.parse(till);
    long diff = date2.getDate() - date1.getDate();
  
    
        try {
             //code for connectivity
             Class.forName("java.sql.DriverManager");
             Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/factory","root","qwerty");
             Statement s=(Statement)c.createStatement();
             Statement s1=(Statement)c.createStatement();
             String A="Select eid from  emp where eid ="+t1.getText()+";";
             String B="Select max(leaveid) from leaventry;";
        ResultSet rs2 = s1.executeQuery(B);
             
        
        if(rs2.next()){
            int id = rs2.getInt(1);            
            id++;
            Leaveid = String.valueOf(id);
        }
            ResultSet rs1 = s.executeQuery(A);
        if(rs1.next()){
        String query = " insert into leaventry (leaveid,eid,ename,frm,till,reason,leavenum)"
        + " values (?, ?, ?, ?, ?, ?, ?)";

      // create the mysql insert preparedstatement
      PreparedStatement preparedStmt = c.prepareStatement(query);
      preparedStmt.setString (1, Leaveid);
      preparedStmt.setString (2, eid);
      preparedStmt.setString (3, ename);
      preparedStmt.setString (4, frm);
      preparedStmt.setString (5, till);
      preparedStmt.setString (6, reason);
      preparedStmt.setLong   (7, diff);
     
      // execute the preparedstatement
      preparedStmt.execute();
   JOptionPane.showMessageDialog(null,"entry added");}
else{
    JOptionPane.showMessageDialog(null,"No employee found");
}  
         
       
         } 
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(this,e);
         }
  




    }//GEN-LAST:event_b3ActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        new adminblock() .setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaveentry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private datechooser.beans.DateChooserCombo c1;
    private datechooser.beans.DateChooserCombo c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables

}
